src/Entity/Players.php
<?php

namespace App\Entity;

use App\Repository\PlayersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayersRepository::class)]
class Players
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'integer')]
    private $age;

    #[ORM\Column(type: 'integer')]
    private $height;

    #[ORM\Column(type: 'string', length: 255)]
    private $nationality;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo;

    #[ORM\Column(type: 'string', length: 255)]
    private $prefered_role;

    #[ORM\ManyToOne(targetEntity: Club::class, inversedBy: 'players')]
    private $team;

    #[ORM\Column(type: 'boolean')]
    private $isTitular;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $position_x;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $position_y;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPreferedRole(): ?string
    {
        return $this->prefered_role;
    }

    public function setPreferedRole(string $prefered_role): self
    {
        $this->prefered_role = $prefered_role;

        return $this;
    }

    public function getTeam(): ?Club
    {
        return $this->team;
    }

    public function setTeam(?Club $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getIsTitular(): ?bool
    {
        return $this->isTitular;
    }

    public function setIsTitular(bool $isTitular): self
    {
        $this->isTitular = $isTitular;

        return $this;
    }

    public function getPositionX(): ?int
    {
        return $this->position_x;
    }

    public function setPositionX(?int $position_x): self
    {
        $this->position_x = $position_x;

        return $this;
    }

    public function getPositionY(): ?int
    {
        return $this->position_y;
    }

    public function setPositionY(?int $position_y): self
    {
        $this->position_y = $position_y;

        return $this;
    }
}

src/Form/PlayersType.php
<?php

namespace App\Form;

use App\Entity\Club;
use App\Entity\Players;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;

class PlayersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lastname', TextType::class, [
                'label' => 'Nom'
            ])
            ->add('firstname', TextType::class, [
                'label' => 'Prénom'
            ])
            ->add('age', IntegerType::class, [
                'label' => 'Age'
            ])
            ->add('height', IntegerType::class, [
                'label' => 'Taille'
            ])
            ->add('nationality', TextType::class, [
                'label' => 'Nationalité'
            ])
            ->add('photo', FileType::class, [
                'label' => 'Photo',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new NotBlank([
                        'message' => 'Ajouter une photo svp'
                    ]),
                    new File([
                        'maxSize' => '3M',
                        'mimeTypesMessage' => 'Format invalide'
                    ])
                ]
            ])
            ->add('prefered_role', ChoiceType::class, [
                'choices' => [
                    'Gardien' => 'Gardien',
                    'Défenseur' => 'Défenseur',
                    'Milieu' => 'Milieu',
                    'Attaquant' => 'Attaquant'
                ]
            ])
            ->add('team', EntityType::class, [
                'label' => "Equipe",
                'class' => Club::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('club')
                        ->orderBy('club.name', 'ASC');
                },
                'choice_label' => 'Name'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Players::class,
        ]);
    }
}

src/Controller/PlayersController.php
<?php

namespace App\Controller;


use App\Entity\Players;
use App\Form\PlayersType;
use App\Form\PlayersTypeEdit;
use App\Repository\PlayersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/players')]
class PlayersController extends AbstractController
{
    #[Route('/', name: 'app_players_index' ,methods: ['GET'])]
    public function index(PlayersRepository $playersRepository): Response
    {
        return $this->render('players/index.html.twig', [
            'players' => $playersRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_new_players', methods: ['GET','POST'])]
    public function new(Request $request, PlayersRepository $playersRepository, SluggerInterface $slugger):Response
    {
        $players = new Players();

        $form = $this->createForm(PlayersType::class,$players);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
				$file = $form->get('photo')->getData();
				$filename = md5(uniqid()) . '.' . $file->guessExtension();
				$file->move($this->getParameter('upload_directory'), $filename);
				$players
					->setPhoto($filename);

            $playersRepository->add($players);
            return $this->redirectToRoute('app_players_index', [],Response::HTTP_SEE_OTHER);

        }

        return $this->renderForm('players/new.html.twig', [
            'players'=>$players,
            'form'=>$form,
        ]);

    }

    #[Route('/{id}', name: 'app_players_show' , methods: ['GET'])]
    public function show(Players $players, PlayersRepository $playersRepository): Response
    {
		$playerss = $playersRepository->findBy(['isTitular' => 1]);
        return $this->render('players/show.html.twig', [
            'players'=>$players,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_players_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Players $players, PlayersRepository $playersRepository): Response
    {


        $form = $this->createForm(PlayersTypeEdit::class, $players);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
		        if ($form->get('photo')->getData()) {
			        $file = $form->get('photo')->getData();
			        $filename = md5(uniqid()) . '.' . $file->guessExtension();
			        $file->move($this->getParameter('upload_directory'), $filename);
			        $players
				        ->setPhoto($filename);
		        }
				if ($form->get('isTitular')->getData() == false) {
					$players
						->setIsTitular(false);
				}elseif($form->get('isTitular')->getData() == true) {
					$players
						->setIsTitular(true);
				}
            $playersRepository->add($players);
            return $this->redirectToRoute('app_players_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('players/edit.html.twig', [
            'players' => $players,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_players_delete', methods: ['POST'])]
    public function delete(Request $request, Players $players, PlayersRepository $playersRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$players->getId(), $request->request->get('_token'))) {
            $playersRepository->remove($players);
        }

        return $this->redirectToRoute('app_players_index', [], Response::HTTP_SEE_OTHER);
    }

	#[Route('/updatePlayerPosition/{id}', name:"updatePlayerPosition", methods:["POST"])]
	public function updatePosition(Request $request,
	                                PlayersRepository $playersRepository)
	{
		$data = json_decode($request->getContent());
		$playerId = $data->playerId;
		$x = $data->x;
		$y = $data->y;
		$player = $playersRepository->findOneBy(['id' => $playerId]);
		$playerX = $player->getPositionX();
		$playerY = $player->getPositionY();
		if($x && $y){
			$doublure = $playersRepository->findOneBy(['position_x' => $x, 'position_y' => $y]);
			if ($doublure){
				$doublureX = $doublure->getPositionX();
				$doublureY = $doublure->getPositionY();
				if($doublureX && $doublureY && !$playerX && !$playerY){
					$doublure->setIsTitular(0);
				}
				$doublure->setPositionX($playerX);
				$doublure->setPositionY($playerY);
				$playersRepository->add($doublure);
			}

			$player->setPositionX($x);
			$player->setPositionY($y);
			$player->setIsTitular(1);
		}else{
			$player->setPositionX(null);
			$player->setPositionY(null);
			$player->setIsTitular(0);
		}
		$playersRepository->add($player);
		$titular = $playersRepository->findBy(['isTitular'=>1]);
		$team = count($titular);
		if ($team < 11){
			return  new Response('Il manque un joueur sur le terrain');
		}elseif ($team > 11){
			return new Response('Vous avez trop de joueurs sur le terrain');
		}else {
			return new Response('Changement effectué', 200);
		}
	}
}

templates/players/_delete_form.html.twig
<form method="post" action="{{ path('app_players_delete', {'id': players.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer ce joueur?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ players.id) }}">
    <button class="delete">Supprimer</button>
</form>

templates/players/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="action">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/players/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Players{% endblock %}

{% block body %}
    <div class="editPlayer">
        <h1>Modifier les données du joueur</h1>
    {{ include('players/_form.html.twig', {'button_label': 'Valider'}) }}
        <div class="return">
            <button>
            <a href="{{ path('app_players_index') }}">Retour à la liste</a>
            </button
    {{ include('players/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/players/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueurs{% endblock %}

{% block body %}
<section>

<h1>Mes joueurs</h1>
    <table class="playersTable">
        <thead>
            <tr>
                <th>Nom</th>
                <th class="minSize">Prénom</th>
                <th>Equipe</th>
                <th class="minSize">Age</th>
                <th class="minSize">Taille</th>
                <th class="minSize">Nationalité</th>
                <th class="indexPhoto">Photo</th>
                <th class="minSize ">Poste préféré</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for player in players %}
            <tr>
                <td class="identity">{{ player.lastname }}</td>
                <td class="identity minSize">{{ player.firstname }}</td>
                <td>{{ player.team.name }}</td>
                <td class="minSize">{{ player.age }} ans</td>
                <td class="minSize">{{ player.height }} cm</td>
                <td class="identity minSize"><img class="flag" src="https://flagcdn.com/w640/{{ player.nationality|lower }}.png" alt="{{ player.nationality }}"></td>
                <td class="indexPhoto"><img class="IdPhoto" src="{{ asset('upload_directory/' ~ player.photo) }}" alt=""></td>
                <td class="minSize">{{ player.preferedRole }}</td>
                <td>
                <button class="playersTable">
                    <a href="{{ path('app_players_show', {'id': player.id}) }}">Voir le joueur</a>
                </button>
                <button class="playersTable">
                    <a href="{{ path('app_players_edit', {'id': player.id}) }}">Modifier</a>
                </button>
                </td>
            </tr>
        {% else %}
            <tr colspan="4"><td>Pas de joueur enregistré</td></tr>
        {% endfor %}
            <tr>
                <td>
                <button class="playersTable">
                <a href="{{ path('app_new_players') }}">Ajouter un joueur</a>
                </button>
                </td>
            </tr>
        </tbody>
    </table>
</section>
{% endblock %}

templates/players/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau joueur{% endblock %}

{% block body %}
    <div class="newPlayer">

    <h1>Ajouter un joueur</h1>

    {{ include('players/_form.html.twig') }}

    <a class="returnToList" href="{{ path('app_players_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/players/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueur{% endblock %}

{% block body %}
    <div class="showPlayerContainer">
        <div class="showPlayerCard">

        <div class="showPlayerBack">
            <div class="identityShow">
                <h2>{{ players.lastname }} </h2>
                <h2> {{ players.firstname }}</h2>
            </div>
            <div><img class="showImg" src="{{ asset('upload_directory/' ~ players.photo) }}" alt=""></div>
            <div class="infoPlayers">
                <div class="divers">
                <div>
                    <h4>Age</h4>
                    <p>{{ players.age }} ans</p>
                </div>
                <div>
                    <h4>Taille</h4>
                    <p>{{ players.height }} cm</p>
                </div>
                </div>
                <div>
                    <h4>Poste préféré</h4>
                    <p>{{ players.preferedRole }}</p>
                </div>
            </div>

                <h4>Actions</h4>
            <div class="actionPlayer">
                <a href="{{ path('app_players_index') }}">
            <button class="btn1">
                    Retour à la liste
            </button>
                </a>
                <a href="{{ path('app_players_edit', {'id': players.id}) }}">
            <button class="btn2">
                    Modifier
            </button>
                </a>
                {{ include('players/_delete_form.html.twig') }}
            </div>
        </div>
        <div class="showPlayerFront">
                <div class="nation">
                    <img class="flag" src="https://flagcdn.com/256x192/{{ players.nationality|lower }}.png" alt="{{ players.nationality }}">
                </div>

            </div>
        </div>
    </div>
{% endblock %}