src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClubRepository::class)]
class Club
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $stade;

    #[ORM\OneToOne(targetEntity: Logo::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private $logo;

    #[ORM\Column(type: 'string', length: 255)]
    private $pelouse;

    #[ORM\Column(type: 'integer')]
    private $places;

    #[ORM\Column(type: 'string', length: 255)]
    private $couverture;

    #[ORM\OneToMany(mappedBy: 'team', targetEntity: Players::class)]
    private $players;

    public function __construct()
    {
        $this->players = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStade(): ?string
    {
        return $this->stade;
    }

    public function setStade(?string $stade): self
    {
        $this->stade = $stade;

        return $this;
    }


    public function getLogo(): ?Logo
    {
        return $this->logo;
    }

    public function setLogo(Logo $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getPelouse(): ?string
    {
        return $this->pelouse;
    }

    public function setPelouse(string $pelouse): self
    {
        $this->pelouse = $pelouse;

        return $this;
    }

    public function getPlaces(): ?int
    {
        return $this->places;
    }

    public function setPlaces(int $places): self
    {
        $this->places = $places;

        return $this;
    }

    public function getCouverture(): ?string
    {
        return $this->couverture;
    }

    public function setCouverture(string $couverture): self
    {
        $this->couverture = $couverture;

        return $this;
    }

    /**
     * @return Collection<int, Players>
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(Players $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players[] = $player;
            $player->setTeam($this);
        }

        return $this;
    }

    public function removePlayer(Players $player): self
    {
        if ($this->players->removeElement($player)) {
            // set the owning side to null (unless already changed)
            if ($player->getTeam() === $this) {
                $player->setTeam(null);
            }
        }

        return $this;
    }


}

src/Entity/Players.php
<?php

namespace App\Entity;

use App\Repository\PlayersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlayersRepository::class)]
class Players
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'integer')]
    private $age;

    #[ORM\Column(type: 'integer')]
    private $height;

    #[ORM\Column(type: 'string', length: 255)]
    private $nationality;

    #[ORM\Column(type: 'string', length: 255)]
    private $photo;

    #[ORM\Column(type: 'string', length: 255)]
    private $prefered_role;

    #[ORM\ManyToOne(targetEntity: Club::class, inversedBy: 'players')]
    private $team;

    #[ORM\Column(type: 'boolean')]
    private $isTitular;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $position_x;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $position_y;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPreferedRole(): ?string
    {
        return $this->prefered_role;
    }

    public function setPreferedRole(string $prefered_role): self
    {
        $this->prefered_role = $prefered_role;

        return $this;
    }

    public function getTeam(): ?Club
    {
        return $this->team;
    }

    public function setTeam(?Club $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getIsTitular(): ?bool
    {
        return $this->isTitular;
    }

    public function setIsTitular(bool $isTitular): self
    {
        $this->isTitular = $isTitular;

        return $this;
    }

    public function getPositionX(): ?int
    {
        return $this->position_x;
    }

    public function setPositionX(?int $position_x): self
    {
        $this->position_x = $position_x;

        return $this;
    }

    public function getPositionY(): ?int
    {
        return $this->position_y;
    }

    public function setPositionY(?int $position_y): self
    {
        $this->position_y = $position_y;

        return $this;
    }
}

src/Form/ClubType.php
<?php

namespace App\Form;

use App\Entity\Club;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;

class ClubType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name',TextType::class,[
                'label'=>'Nom'
            ])
            ->add('stade', TextType::class, [
                'label'=>'Stade'
            ])
            ->add('logo',FileType::class,[
                'label'=>'Logo',
                'mapped'=>false,
                'required'=>false,
                'constraints'=> [
                    new NotBlank([
                        'message'=> 'Renseigner un logo svp'
                    ]),
                    new File([
                        'maxSize' => '3M',
                        'mimeTypesMessage' => 'Format invalide'
                    ])
                ]
            ])

            ->add('pelouse', ChoiceType::class,[
                'choices'=>[
                    'Naturelle'=>'Naturelle',
                    'Synthétique'=>'Synthétique',
                ]
            ])
            ->add('places', IntegerType::class,[
                'label'=>'PLaces'
            ])
            ->add('couverture',ChoiceType::class,[
                'choices'=>[
                    'couvert'=> 'Couvert',
                    'semi couvert'=> 'Semi couvert',
                    'non couvert'=> 'Non couvert',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Club::class,
        ]);
    }
}

src/Controller/ClubController.php
<?php

namespace App\Controller;

use App\Entity\Club;
use App\Entity\Logo;
use App\Form\ClubType;
use App\Repository\ClubRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

#[Route('/club')]
class ClubController extends AbstractController
{
    #[Route('/', name: 'app_club_index', methods: ['GET'])]
    public function index(ClubRepository $clubRepository): Response
    {
        return $this->render('club/index.html.twig', [
            'clubs' => $clubRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_club_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ClubRepository $clubRepository, SluggerInterface $slugger): Response
    {
        $club = new Club();
        $logo = new Logo();

        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('logo')->getData();
                #$originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                #$safeFilename = $slugger->slug($originalFilename);
                #$newFilename = $safeFilename. '.' .uniqid(). '.' .$file->guessExtension();
            # Même procédure que ci-dessus mais plus rapide
                $filename = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move($this->getParameter('upload_directory'), $filename);
            $logo
                ->setName($filename)
                ->setAlt('mon logo');
            $club
                ->setLogo($logo);
            $clubRepository->add($club);
            return $this->redirectToRoute('app_club_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('club/new.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_show', methods: ['GET'])]
    public function show(Club $club): Response
    {
        dump($club->getPlayers());
        return $this->render('club/show.html.twig', [
            'club' => $club,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_club_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Club $club, ClubRepository $clubRepository): Response
    {
        $logo = new Logo();

        $form = $this->createForm(ClubType::class, $club);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('logo')->getData();

            $filename = md5(uniqid()) . '.' . $file->guessExtension();
            $file->move($this->getParameter('upload_directory'), $filename);

            $logo
                ->setName($filename)
                ->setAlt('mon logo');
            $club
                ->setLogo($logo);
            $clubRepository->add($club);
            return $this->redirectToRoute('app_club_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('club/edit.html.twig', [
            'club' => $club,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_club_delete', methods: ['POST'])]
    public function delete(Request $request, Club $club, ClubRepository $clubRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$club->getId(), $request->request->get('_token'))) {
            $clubRepository->remove($club);
        }

        return $this->redirectToRoute('app_club_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/club/_delete_form.html.twig
{% if club.players|length == 0 %}
<form method="post" action="{{ path('app_club_delete', {'id': club.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer ce club?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ club.id) }}">
    <button class="btn">Supprimer</button>
</form>
{% endif %}

templates/club/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="action">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/club/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Club{% endblock %}

{% block body %}
    <div class="update">

    <h1>Modifier Club</h1>

    {{ include('club/_form.html.twig', {'button_label': 'Modifier'}) }}
<button>
    <a href="{{ path('app_club_index') }}">Retour à la liste</a>
</button>
    {{ include('club/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/club/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club index{% endblock %}

{% block body %}
    <article class="club">
    <h1>Index de mon(mes) Club(s)</h1>
        {% for club in clubs %}
               <h2 class="clubTitle">{{ club.name }}</h2>
            <div class="clubCard">
                <img class="logo" src="{{ asset('upload_directory/' ~ club.logo.name) }}" alt="{{ club.logo.alt }}">
                <div class="stade">
                    <h3><img src="{{ asset('assets/img/logostade.jpg') }}" alt="logo de stade"> Stade {{ club.stade }}</h3>
                    <p> pelouse {{ club.pelouse }}</p>
                    <p>{{ club.places }} places</p>
                    <p>{{ club.couverture }}</p>
                </div>
                    <div class="teamsIndex">
                    <h3><img src="{{ asset('assets/img/logomaillot.png') }}" alt="logo de maillot"> joueurs </h3>
                    {% for player in club.players %}
                    <p>{{ player.firstname }} {{player.lastname}} </p>
                    {% endfor %}
                    </div>
                <div class="action">
                    <button>
                    <a href="{{ path('app_club_show', {'id': club.id}) }}">Voir le club</a>
                    </button>
                    <button>
                    <a href="{{ path('app_club_edit', {'id': club.id}) }}">Modifier</a>
                    </button>
                </div>

            </div>
        {% else %}
                <p>Pas d'équipe enregistrée</p>
        {% endfor %}
    <button>
    <a href="{{ path('app_club_new') }}">Créer un nouveau club</a>
    </button>

    </article>
{% endblock %}

templates/club/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Club{% endblock %}

{% block body %}
    <div class="newClub">

    <h1>Create new Club</h1>

    {{ include('club/_form.html.twig') }}

    <a class="returnToList" href="{{ path('app_club_index') }}">Retour à la liste</a>
    </div>
{% endblock %}

templates/club/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Club{% endblock %}

{% block body %}
<article>
    <h1>Club</h1>
        <div class="showClub">
            <div class="showTeam">
                    <p><img class="showImg" src="{{ asset('upload_directory/' ~ club.logo.name) }}" alt="{{ club.logo.alt }}"></p>
                    <p>{{ club.name }}</p>
            </div>
            <div class="showClubInfo">
            <div class="teams">
                {% for y in 1..9 %}
                    {% for x in 1..5 %}
                        <div class="js-area" data-x="{{ x }}" data-y="{{ y }}" style="grid-area: {{ y }} / {{ x }} / {{ y + 1 }} / {{ x + 1 }}">
                            {% for player in club.players %}
                                {% if player.isTitular and player.positionX == x and player.positionY == y %}
                                    <div class="player" data-id="{{ player.id }}">
                                        <div class="player-name">{{player.lastname}}</div>
                                        <img class="player-img" src="{{ asset('assets/img/logomaillot.png') }}" alt="logo de maillot" />
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endfor %}
                {% endfor %}


            </div>

            <div class="notTitular">
                <h2>Remplaçants</h2>
                <div class="js-area">
                    {% for player in club.players %}
                        {% if not player.isTitular or player.positionX == null or player.positionY == null %}
                            <div class="player" data-id="{{ player.id }}">
                                <div class="player-name">{{player.lastname}}</div>
                                <img class="player-img" src="{{ asset('assets/img/logomaillot.png') }}" alt="logo de maillot" />
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div class="teamsMini">
                <h2>Equipe <img src="{{ asset('assets/img/logomaillot.png') }}" alt="logo de maillot"></h2>
                {% for player in club.players %}
                <div>{{ player.lastname }}</div>
                {% endfor %}
            </div>

            <div class="stade">
                <h2> Stade <img src="{{ asset('assets/img/logostade.jpg') }}" alt="logo de stade"></h2>
                <p>{{ club.stade }}</p>

                <h4>Pelouse <img src="{{ asset('assets/img/terrain.png') }}" alt="pelouse"></h4>
                <p>{{ club.pelouse }}</p>

                <h4>Places <img src="{{ asset('assets/img/tribune.png') }}" alt="tribune"></h4>
                <p>{{ club.places }}</p>

                <h4>Couverture <img src="{{ asset('assets/img/parasol.png') }}" alt="parasol"></h4>
                <p>{{ club.couverture }}</p>
            </div>
            <div class="actionClub">
                <h2>Actions</h2>
                <button>
                    <a href="{{ path('app_club_index') }}">Retour à la liste</a>
                </button>
                <button>
                    <a href="{{ path('app_club_edit', {'id': club.id}) }}">Modifier</a>
                </button>
                 {{ include('club/_delete_form.html.twig') }}
            </div>
        </div>
        </div>
    </article>

    <script>
        (() => {
            const $teams = document.body.querySelector('.teams');
            const $players = document.body.querySelectorAll('.player');
            const $areas = document.body.querySelectorAll('.js-area');

	        $players.forEach($player => {
		        $player.addEventListener('mousedown', (event) => {
                    const origin = { x: event.clientX, y: event.clientY };
			        const $originArea = $player.parentElement;

		            event.preventDefault();

                    const moveFn = (event) => {
                        const target = { x: event.clientX, y: event.clientY };

						$areas.forEach($area => {
							const rect = $area.getBoundingClientRect();
							const hover = target.x >= rect.x && target.x <= rect.x + rect.width && target.y >= rect.y && target.y <= rect.y + rect.height;

							hover ? $area.classList.add('selected') : $area.classList.remove('selected');
                        })

	                    $player.style.transform = `translate(${target.x - origin.x}px, ${target.y - origin.y}px)`;
                    };

                    const upFn = (event) => {
	                    window.removeEventListener('mousemove', moveFn);
	                    window.removeEventListener('mouseup', upFn);

						$areas.forEach($area => $area.classList.remove('selected'));
	                    $player.style.transform = `none`;

	                    const target = { x: event.clientX, y: event.clientY };

						for (const $area of $areas) {
							if ($area === $player.parentElement)
							    continue;

                            const rect = $area.getBoundingClientRect();

                            if (target.x >= rect.x && target.x <= rect.x + rect.width && target.y >= rect.y && target.y <= rect.y + rect.height) {
                                const x = $area.dataset.x || null;
                                const y = $area.dataset.y || null;

                                const titulars = $teams.querySelectorAll('.player').length;
                                const areaPlayers = $area.children.length;

                                if (!$originArea.dataset.x && titulars - areaPlayers + 1 > 11) {
                                    alert('Trop de joueurs sur le terrain');
                                    return;
                                }

								if (x === null && titulars - 1 < 11) {
									alert('Il manque un joueur');
									return;
                                }

                                console.log(x, y, $player)
                                if (x !== null && y !== null)
                                    for (const $child of $area.children)
                                        $originArea.appendChild($child);

                                $area.appendChild($player);

                                const data = {
                                    playerId: $player.dataset.id,
                                    x: x,
                                    y: y
                                }
                                const url = `/hackathon2/public/players/updatePlayerPosition/${$player.dataset.id}`
                                fetch(url,{
                                    method:'POST',
                                    headers: { 'Content-Type': 'application/json' },
                                    body: JSON.stringify(data)
                                }).then( (res)=>{
                                    console.log(res);
                                    if(res.ok === true){

                                    // }else if(response.message == ''){
                                    // 	console.log('Error')
                                    }
                                })
                                return;
                            }
                        }
                    };

                    window.addEventListener('mousemove', moveFn);
                    window.addEventListener('mouseup', upFn);
                });
            })
        })();

    </script>

{% endblock %}